### ISSUE TITLE
Size and color position

### ISSUE THREAD

**Issue by BDVGitHub** [iconify/iconify-penpot#1]
Hey, thanks for the handy plugin, for selecting colours I have the following suggestion:

On the website, size and colour are listed below each other. As you can see in the picture below.
![afbeelding](https://github.com/user-attachments/assets/9667c5e5-be07-4a8e-ad27-ac946aaba069)
In the plugin, size and colour are next to each other. Is it possible to put them under each other like on the site so that everything is uniform? Now I keep looking under size to select a colour because I'm used to this from the website, but I can't find it again. A little later I remember that it is next to size in the plugin. 
![afbeelding](https://github.com/user-attachments/assets/3dda50ab-b006-4d58-a5e4-55fc4fbc4623)

**Comment by cyberalien** [comment]
Thanks for suggestion, but it won't work.

On website on the right side there is a code sample, which limits horizontal space, but vertical space is available because code samples are longer.

In plugin vertical space is limited because window is small and should show as many icons as possible, but horizontal space in footer is available, so size and color can fit on the same row.

Additionally, on website there are more customisation options, depending on icon. Your example is the basic icon that only has one color.

On website you can customise not only `currentColor`, but also other colors, opacity, stroke width and animation speed. All of those options are not available in plugin.

If there is at least one more customisation option, layout used in plugin will not longer work. Then it will have inconsistent layout: one row if there is only one color, multiple rows for multiple colors. That's worse solution than having different layout between plugin and website.
